#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: lab help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help lab
fi

lasher _help lab "$command"
